CREATE DATABASE IF NOT EXISTS csmeli;

USE csmeli;

CREATE TABLE IF NOT EXISTS users (
    id INT(6) NOT NULL AUTO_INCREMENT PRIMARY KEY,
    user VARCHAR(30) NOT NULL,
    email VARCHAR(30) NOT NULL,
    pass VARCHAR(100) NOT NULL,
    apiToken VARCHAR(100) NOT NULL,
    admin BOOLEAN
);

CREATE TABLE IF NOT EXISTS blacklist (
    ip VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS whitelist (
    ip VARCHAR(100) NOT NULL
);